# Generated by Django 5.2.6 on 2025-09-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='calories_target',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calorie_target',
            field=models.FloatField(default=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='carbs_target',
            field=models.FloatField(default=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fat_target',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='protein_target',
            field=models.FloatField(default=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_goal',
            field=models.FloatField(),
        ),
    ]
