# Generated by Django 5.2.6 on 2025-09-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_userprofile_calories_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='date',
        ),
    ]
