# Generated by Django 5.2.6 on 2025-09-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
