# Generated by Django 5.2.6 on 2025-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_foodentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
