# Generated by Django 5.2.6 on 2025-09-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_foodentry_calories_alter_foodentry_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'Uncategorized'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], default='uncategorized', max_length=20),
        ),
    ]
