# Generated by Django 5.2.6 on 2025-09-18 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_foodentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
